Added Wireframes
PSUCapstone2023-Group1/Clean-Energy-PA pull request #7
Opened 2023-06-03 11:32 UTC by PunkChameleon

Wireframe documentation for several user stories.

2023-06-03 16:31 UTC, RigatoniRex commented on documentation/.$Wireframes.drawio.dtmp
We can probably delete this temp file. Should also add this extension to the .gitignore file.

2023-06-03 16:48 UTC, PunkChameleon commented on .gitignore
> +.$Wireframes.drawio.dtmp
@RigatoniRex -- good points, cleaned up!

2023-06-03 16:50 UTC, RigatoniRex approved these changes
Looks good!

2023-06-03 17:24 UTC, vtattyba approved these changes

2023-06-03 17:25 UTC, RigatoniRex requested changes
Just noticed that your wireframes use "first name" and "last name" instead of username, which is what we had in our ER diagram. We may want to resolve this first before we merge this.

We should either:
1. Modify the wireframe to use username
2. Update the ER to store first name/ last name

2023-06-04 01:07 UTC, PunkChameleon commented
Good catch @RigatoniRex ! In my head, I'm not sure username makes sense if we can guid by email. We won't really need the username post login or do much with it. I'd vote the second of the two options, but I'm totally open if we think there's value for the username too.

2023-06-04 16:15 UTC, RigatoniRex commented
> Good catch @RigatoniRex ! In my head, I'm not sure username makes sense if we can guid by email. We won't really need the username post login or do much with it. I'd vote the second of the two options, but I'm totally open if we think there's value for the username too.

Sounds good! I'll update the ER. We need to make sure we aren't using username anywhere else too.

2023-06-04 16:15 UTC, RigatoniRex approved these changes

2023-06-04 16:17 UTC, merged